name: "Zig CI"
description: "A modular Zig CI"

author: "pathum25"
branding:
  icon: "package"
  color: "yellow"

inputs:
  zig-version:
    description: "Zig version"
    required: false
    default: "0.16.0"
  working-directory:
    description: "Root directroy"
    required: false
    default: "."
  command-test:
    description: "Build test command"
    required: false
    default: "zig build test"
  failure-on-error:
    description: "Return an Action Failure on error"
    required: false
    default: "true"

runs:
  using: "node24"
  main: "dist/index.js"
