name: "Zig CI"
description: "A modular Zig CI"

author: "YetAnotherMechanicusEnjoyer"
branding:
  icon: "package"
  color: "yellow"

inputs:
  zig-version:
    description: "Zig version"
    required: false
    default: "0.16.0"
  working-directory:
    description: "Root directroy"
    required: false
    default: "."
  command-test:
    description: "Build test command"
    required: false
    default: "zig build test"

runs:
  using: "composite"
  steps:
    - name: Zig Setup
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ inputs.zig-version }}

    - name: Zig CI
      shell: bash
      env:
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_COMMAND_TEST: ${{ inputs.command-test }}
      run: node ${{ github.action_path }}/dist/index.js
