name: "Zig CI"
description: "A modular Zig CI"

author: "YetAnotherMechanicusEnjoyer"
branding:
  icon: "package"
  color: "yellow"

inputs:
  zig-version:
    description: "Zig version"
    required: false
    default: "0.16.0"
  working-directory:
    description: "Root directroy"
    required: false
    default: "."
  command-test:
    description: "Build test command"
    required: false
    default: "zig build test"

runs:
  using: "node20"
  main: "dist/index.js"
