name: Test Failing CI
run-name: Test Failing CI
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Failing Without Action Failure Zig CI
        uses: ./ci
        with:
          zig-version: "0.16.0"
          working-directory: "./tests"
          command-test: "zig test error.zig"
          failure-on-error: "false"

      - name: Failing Zig CI
        uses: ./ci
        with:
          zig-version: "0.16.0"
          working-directory: "./tests"
          command-test: "zig test error.zig"
