name: Test Zig Docs CD
run-name: Test Zig Docs CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: YetAnotherMechanicusEnjoyer/zig-actions/docs@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zig-version: "0.16.0"
          working-directory: "./tests/docs"
          command-docs: "zig build docs"
          docs-folder: "zig-out/docs"
