name: Test Successful CI
run-name: Test Successful CI
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Successful Zig CI
        uses: ./ci
        with:
          zig-version: "0.16.0"
          working-directory: "./tests/ci"
          command-test: "zig test success.zig"
